### ISSUE TITLE
Retrieving a nullable `ValueTuple` always returns null

### ISSUE THREAD

**Issue by simonmckenzie** [StackExchange/Dapper#1108]
Hi,

If I retrieve an existing record using a valuetuple, I receive the record as expected, but if I change to a nullable valuetuple (as I would like to using `QueryFirstOrDefault`), the result is always null:

```csharp
var valueTuple = connection.QuerySingle<(int id, string name)>("select 42, 'Fred'");
// Returns value as expected

var nullableValueTuple = connection.QuerySingle<(int id, string name)?>("select 42, 'Fred'");
// Returns null
```

**Comment by mgravell** [comment]
this seems like a brain-dead issue by me - I'll change the shape recognition code

**Comment by simonmckenzie** [comment]
Thanks Marc!

**Comment by benbryant0** [comment]
This appears to still be happening as of 2.0.30. Any update?

**Comment by NickCraver** [comment]
Fixed in #1400, thanks @JulianRooze!

**Comment by shoe-diamente** [comment]
The linked PR doesn't seem to fix `QueryFirstOrDefault` nor `QueryFirstOrDefaultAsync` nor `QuerySingleOrDefaultAsync`.
Aren't those supposed to work similarly? I'm currently using `2.0.35` and `QueryFirstOrDefaultAsync` always returns `null` for a `ValueTuple`.

**Comment by JulianRooze** [comment]
@shoe-diamente All those methods call the same underlying code AFAIK so this fix should work for them all, but it would maybe be good to add some assertions for those as well. However, 2.0.35 was released before the #1400 PR was merged so it's not in there yet.

**Comment by shoe-diamente** [comment]
I see, thanks.
